# Generated by Django 4.2.11 on 2026-04-24 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
        ('schedules', '0001_initial'),
        ('attendance', '0002_attendance_schedule'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('enrollment', 'schedule', 'date')},
        ),
    ]
