# Generated by Django 4.2.11 on 2026-05-11 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_remove_class_schedule_class_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
